# Generated by Django 4.1.1 on 2022-09-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_subject_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='quota',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
    ]
